$wallpaper_path= ~/.local/share/wallpapers/space.jpg

wallpaper {
    monitor = DP-1
    path = $wallpaper_path
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = $wallpaper_path
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = $wallpaper_path
    fit_mode = cover
}

# # enable splash text rendering over the wallpaper
splash = false
ipc = off
